### ISSUE TITLE
Can't run scancode in ArchLinux with libffi-3.3-3

### ISSUE THREAD

**Issue by JRavi2** [aboutcode-org/scancode-toolkit#2014]
### Description

I just did a full system update, which included upgrading libffi from 3.2.1-4 to 3.3-3. But after that I can't run scancode. Just running `./scancode --help` gives the following error:

```========================================================================
ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
The following plugin(s) are referenced and cannot be loaded/imported:
libffi.so.6: cannot open shared object file: No such file or directory
========================================================================
Traceback (most recent call last):
  File "/home/ravi/scancode-toolkit/bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "/home/ravi/scancode-toolkit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ravi/scancode-toolkit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/ravi/scancode-toolkit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/ravi/scancode-toolkit/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ravi/scancode-toolkit/src/scancode/cli.py", line 229, in <module>
    raise e
  File "/home/ravi/scancode-toolkit/src/scancode/cli.py", line 216, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/home/ravi/scancode-toolkit/src/plugincode/__init__.py", line 190, in load_plugins
    mgr_setup = manager.setup()
  File "/home/ravi/scancode-toolkit/src/plugincode/__init__.py", line 220, in setup
    raise e
  File "/home/ravi/scancode-toolkit/src/plugincode/__init__.py", line 218, in setup
    self.manager.load_setuptools_entrypoints(entrypoint)
  File "/home/ravi/scancode-toolkit/lib/python3.6/site-packages/pluggy/manager.py", line 292, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/ravi/scancode-toolkit/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 90, in load
    module = import_module(match.group('module'))
  File "/home/ravi/scancode-toolkit/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ravi/scancode-toolkit/src/summarycode/generated.py", line 40, in <module>
    import typecode.contenttype
  File "/home/ravi/scancode-toolkit/src/typecode/__init__.py", line 27, in <module>
    from typecode.contenttype import get_type
  File "/home/ravi/scancode-toolkit/src/typecode/contenttype.py", line 54, in <module>
    from typecode import magic2
  File "/home/ravi/scancode-toolkit/src/typecode/magic2.py", line 51, in <module>
    import ctypes
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

I tried re-configuring and also configuring a fresh clone, with `./configure`, but got the following error :
```* Installing components ...
Looking in links: /home/ravi/scancode-toolkit/thirdparty
Obtaining file:///home/ravi/scancode-toolkit (from -r /home/ravi/scancode-toolkit/etc/conf/requirements_base.txt (line 10))
    ERROR: Command errored out with exit status 1:
     command: /home/ravi/scancode-toolkit/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ravi/scancode-toolkit/setup.py'"'"'; __file__='"'"'/home/ravi/scancode-toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/ravi/scancode-toolkit/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ravi/scancode-toolkit/lib/python3.6/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/ravi/scancode-toolkit/lib/python3.6/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/home/ravi/scancode-toolkit/lib/python3.6/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.6/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "/home/ravi/scancode-toolkit/etc/configure.py", line 552, in <module>
    install_3pp(configs, root_dir, thirdparty_dirs, quiet=quiet)
  File "/home/ravi/scancode-toolkit/etc/configure.py", line 266, in install_3pp
    run_pip(requirements, root_dir, tpp_dirs, quiet)
  File "/home/ravi/scancode-toolkit/etc/configure.py", line 292, in run_pip
    call(pcmd, root_dir)
  File "/home/ravi/scancode-toolkit/etc/configure.py", line 139, in call
    subprocess.check_call(cmd, shell=True, env=dict(os.environ), cwd=root_dir)
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/home/ravi/scancode-toolkit/bin/pip" install --upgrade --no-index --no-cache-dir --find-links="/home/ravi/scancode-toolkit/thirdparty" --requirement "/home/ravi/scancode-toolkit/etc/conf/requirements_base.txt" --requirement "/home/ravi/scancode-toolkit/etc/conf/dev/requirements_base.txt"' returned non-zero exit status 1.
```

Tried downgrading to libffi-3.2.1-4, and everything works perfectly fine.

### How To Reproduce

Install libffi-3.3-3 and then try to re-configure.

### System configuration

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? 3.1.2
* What installation method was used to install/run scancode? source download

**Comment by pombredanne** [comment]
@JRavi2 Thanks, so we need to put an upper version range for this in our setup

**Comment by JRavi2** [comment]
@pombredanne It appears that this issue is not specific to scancode. I just found out at a forum that others are also encountering the same problem since the new libffi update was released for Arch, like [here](https://bugs.archlinux.org/task/66222) and [here](https://bbs.archlinux.org/viewtopic.php?id=254650). I too am having some problems related to libffi, while installing python modules on my system.
I believe this problem localized to Arch users only. A temporary workaround to this for now, that worked for me, would be to install the [libffi6 AUR Package](https://aur.archlinux.org/packages/libffi6/).

**Comment by DennisClark** [comment]
@pombredanne   or @AyanSinhaMahapatra   Is SCTK no longer dependent on libffi ?  I cannot find it in my MacOS installation of scancode-toolkit-v32.3.3 although I see it in earlier versions.  If yes, we can close this issue as being no longer relevant.

**Comment by AyanSinhaMahapatra** [comment]
@DennisClark This seems to be a ArchLinux specific occurrence which was due to some issue external to scancode as mentioned above. We've had folks install and use scancode in arch since then and we've had a lot of updates after this, so we can close this safely. If the issue is seen again, we can re-open easily.
